/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_schematicwrapper_free(a: number, b: number): void;
export function __wbg_blockposition_free(a: number, b: number): void;
export function __wbg_get_blockposition_x(a: number): number;
export function __wbg_set_blockposition_x(a: number, b: number): void;
export function __wbg_get_blockposition_y(a: number): number;
export function __wbg_set_blockposition_y(a: number, b: number): void;
export function __wbg_get_blockposition_z(a: number): number;
export function __wbg_set_blockposition_z(a: number, b: number): void;
export function schematicwrapper_new(): number;
export function schematicwrapper_from_litematic(a: number, b: number, c: number, d: number): void;
export function schematicwrapper_to_litematic(a: number, b: number): void;
export function schematicwrapper_from_schematic(a: number, b: number, c: number, d: number): void;
export function schematicwrapper_to_schematic(a: number, b: number): void;
export function schematicwrapper_set_block(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function schematicwrapper_get_block(a: number, b: number, c: number, d: number, e: number): void;
export function schematicwrapper_print_schematic(a: number, b: number): void;
export function schematicwrapper_debug_info(a: number, b: number): void;
export function schematicwrapper_get_dimensions(a: number, b: number): void;
export function schematicwrapper_get_block_count(a: number): number;
export function schematicwrapper_get_volume(a: number): number;
export function schematicwrapper_get_region_names(a: number, b: number): void;
export function schematicwrapper_blocks(a: number): number;
export function schematicwrapper_chunks(a: number, b: number, c: number, d: number): number;
export function __wbg_blockstatewrapper_free(a: number, b: number): void;
export function blockstatewrapper_new(a: number, b: number): number;
export function blockstatewrapper_with_property(a: number, b: number, c: number, d: number, e: number): void;
export function blockstatewrapper_name(a: number, b: number): void;
export function blockstatewrapper_properties(a: number): number;
export function debug_schematic(a: number, b: number): void;
export function debug_json_schematic(a: number, b: number): void;
export function start(): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
